In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [3]:
lr_model = LogisticRegression()
lr_model.fit(X_train, y_train)
lr_model.score(X_test, y_test)

0.9574074074074074

In [4]:
svm_model = SVC()
svm_model.fit(X_train, y_train)
svm_model.score(X_test, y_test)

0.9833333333333333

In [5]:
rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)
rf_model.score(X_test, y_test)

0.9796296296296296

In [6]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [7]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [8]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [9]:
get_score(LogisticRegression(),X_train, X_test, y_train, y_test)

0.9574074074074074

In [10]:
from sklearn.model_selection import StratifiedKFold

In [11]:
folds = StratifiedKFold(n_splits=3)

In [12]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index,test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test =  digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index] 
    scores_l.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

In [13]:
scores_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [14]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [15]:
scores_rf

[0.9415692821368948, 0.9582637729549248, 0.9282136894824707]

In [16]:
from sklearn.model_selection import cross_val_score

In [17]:
cross_val_score(LogisticRegression(), digits.data, digits.target)

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [18]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [20]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.93055556, 0.91388889, 0.96100279, 0.96935933, 0.9275766 ])

In [21]:
cross_val_score(RandomForestClassifier(n_estimators=30), digits.data, digits.target)

array([0.93333333, 0.9       , 0.94986072, 0.95543175, 0.91086351])

In [22]:
cross_val_score(RandomForestClassifier(n_estimators=50), digits.data, digits.target)

array([0.93888889, 0.88888889, 0.95264624, 0.96100279, 0.91922006])