In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import warnings 
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_excel("price_home.xlsx")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [3]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

3

In [4]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)

In [5]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [6]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms','age']], df.price)

LinearRegression()

In [7]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [8]:
reg.intercept_

383725.0

predict price for home with 3000 area 3 bedrooms and 40 y/d

In [9]:
reg.predict([[3000,3,40]])

array([444400.])

In [10]:
reg.predict([[3000,4,15]])

array([589000.])

In [11]:
137.25 * 3000 + -26025 * 3 + -6825 * 40  + 383725.0

444400.0

In [12]:
reg.predict([[2500,4,5]])

array([588625.])

Exercise(salary): 2yr exp, 9 test score, 6 interview score
                  12yr exp, 10 test score, 10 interview score

In [13]:
df = pd.read_excel("hiring.xlsx")
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [14]:
df.experience = df.experience.fillna("zero")

In [15]:
df

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [16]:
from word2number import w2n

In [17]:
df.experience = df.experience.apply(w2n.word_to_num)

In [18]:
df

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         NaN                7   72000
7          11         7.0                8   80000

In [19]:
test_median = math.floor(df.test_score.median())
df.test_score = df.test_score.fillna(test_median)

In [20]:
df

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [21]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score','interview_score']],df.salary)

LinearRegression()

In [22]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [23]:
reg.intercept_

17737.263464337688

In [24]:
reg.predict([[2, 9, 6]])

array([53205.96797671])

In [25]:
reg.predict([[12, 10, 10]])

array([92002.18340611])